const text="Hello, and welcome to the first ever edition of Straight From the Lore Docs! This will be a mini-series on the Devlog that aims to share a little bit about the lore and story we've been working on for our games. There will be minimal edits, if any, between the actual content on our lore docs and this blog post, so some statements may seem a bit weird or out of context. Don't worry if that's the case, things will start to make sense as more and more of the lore is revealed!  \n  \nFor this first post, we'll be taking a look at the five main protagonists of our story: Don, Morgan, Ivan, Natalia and Victor. The following gives some brief backgrund information about each of these characters. All credits go to Duke of Marlins for writing these.  \n  \n"+
"### Don, the Noble Adventurer  \n"+
"Don began as a lowly farmer, always aspired to be a knight of the realm. Comes from humble beginnings, so he has all the values traditionally associated with knighthood. At least, that’s what he thinks. However, since the Knighthood has rejected him, now for the 5th time in a row, due to failing to be able to ride a horse, they are obviously corrupt servants of the Rich (No duh, Sherlock), and he’s doing it live! If half the mercenaries are frothing berserkers with no skill, then Don, literally a farmer with only basic training in weaponry, can do it!  If not, well he’ll find a way to convince himself of  the most “noble” (Self-serving) action, and be knightley doing it!  \n  \n"+
"### Natalia, the Blade's Heir  \n"+
"Once, she was the daughter of filthy noble pigs, who oppressed the poor for their riches. Such evilness attracted the Black Hand, who purged the demons. But, they had a daughter, a tiny baby, crying at the loss of her parents. She thus was also a demon, but the Black Hand took pity on her. She may be forever tainted by her blood, but Igor himself raised her as his own. Why can’t she be untainted? Igor raised her in the gentle arms of the Black Hand, and she will rebuke all the evils of her existence upon the evil world. She doesn’t know why she was born tainted, but it’s the only way that Igor won’t train her anymore in being normal. She fights for the Black Hand, but in the back of her mind, something doesn’t add up, and she will draw mountains of blood to keep it at bay.    \n  \n"+
"### Morgana, Avatar of the Goddess  \n"+
"A woman with a past as mysterious as her powers. Is she Morgana incarnate? A direct descendant? Or is her name just an extraordinary coincidence? Regardless, she’s a powerful sorceress that few people dare approach, unless they’re hiring her for… \"cleaning\" jobs. She charges a lot of money, but she gets it done.  \n"+
"Also known as the chosen of Morgana, the Goddess of Bloodshed and Glory. Magic prodigee! Actually literally slightly not okay. It turns out being all these things can break a woman, but that’s okay. She got used to it (With a  glass, and burning up half a cathedral, whoops). She can mop the floor with foes, Don’s hypocrisy, Natalia’s mood swings, Victor’s slightly outdated values, and Ivan’s passiveness! What more can she need, aside from oodles of booze? Certainly, not sanity, or wantonly being possessed by a douche Goddess! Oh boy, Morgana needs that bottle now, please, and maybe another one while you’re at it, thank you.  \n  \n"+
"### Ivan and Moxie, the Hopeful Guardians  \n"+
"Born in the frosted mountains of Tolcos, Ivan was always the coolest in the room. He’s a giant, buddy, and there are few things better than a giant. Wait, how about kind Tolcan magic-wielding shieldbearer giant? Find someone cooler than that, huh? Alright, alright, you got him. Moxie is a blue ox his size, and she is the sweetest gal you’ll ever meet, and the only blue animal who uses wind magic around! Ivan’s won prizes for that, he’ll tell ya. Now then, when it comes to combat, Moxie is usually the one ramming and slamming and giving foes blows, because Ivan’s such a great guy, he doesn’t need to fight you, and so he doesn’t, he’s a bona fide pacifist! That’s a dime a dozen, especially in Yoapan, and so’s the people who hold the door, don’t go backstabbing other people for power (DON), …  and keeps talking instead of doing… whoops. Well, Ivan does have Moxie to compensate.  \n  \n"+
"### Victor, Buyer of Souls  \n"+
"Victor worked hard, played hard, to get to the top of the food chain. Rich, powerful, and a firm believer in his ideals. Which is to say laissez-faire everything. He doesn’t really believe in government, so he puts his chips with the men who make do with less. Though his methods are admittedly extreme and somewhat convoluted, such as supplying both sides of a war with funding to lessen the government’s involvement with the people, his goals are noble. He’s even laissez-faire with the ladies, frequently visiting brothels. He’s practicing his old job, being a hit, he likes to reply. Whatever that means, Victor is nonetheless cunning, capable, and charming, the three Cs of the business world.  \n  \n"
export default text;